import os
import shutil
import sys

def main():
    if len(sys.argv) < 2:
        print("Usage: delete-venvs <directory>")
        sys.exit(1)

    base_dir = sys.argv[1]

    if not os.path.isdir(base_dir):
        print(f"{base_dir} is not a valid directory.")
        sys.exit(1)

    for root, dirs, files in os.walk(base_dir):
        if 'venv' in dirs:
            venv_path = os.path.join(root, 'venv')
            print(f"Deleting virtual environment at {venv_path}")
            shutil.rmtree(venv_path)

if __name__ == "__main__":
    main()

